import {useMemo,useState} from 'react'
import {apiRequest} from '../../../services/api'
function extractJson(text){const raw=String(text||'');const fenced=raw.match(/\`\`\`(?:json)?\s*([\s\S]*?)\`\`\`/i)?.[1]||raw;const a=fenced.indexOf('{'),b=fenced.lastIndexOf('}');if(a<0||b<a)return null;try{return JSON.parse(fenced.slice(a,b+1))}catch{return null}}
function validateProposal(value,knownKeys){const errors=[];if(!value||typeof value!=='object'||Array.isArray(value))return ['Assistant response does not contain a valid change proposal.'];if(value.elements!==undefined&&!Array.isArray(value.elements))errors.push('Elements must be an array.');if(value.resources!==undefined&&!Array.isArray(value.resources))errors.push('Resources must be an array.');(value.elements||[]).forEach((e,i)=>{if(!e||typeof e!=='object')errors.push(`Element ${i+1} is invalid.`);else if(!knownKeys.has(String(e.key||'')))errors.push(`Element ${i+1} uses an unsupported Builder element.`)});return errors}
export default function GPTBuilderAIAssistant({flow,elements,resources,elementKeys=[],onApply,onClose,onGenerateTest}){
 const [mode,setMode]=useState('draft'),[prompt,setPrompt]=useState(''),[length,setLength]=useState('standard'),[busy,setBusy]=useState(false),[answer,setAnswer]=useState(''),[proposal,setProposal]=useState(null),[errors,setErrors]=useState([])
 const context=useMemo(()=>({flow,elements:elements.map(e=>({id:e.id,key:e.key,label:e.label,apiName:e.apiName,config:e.config})),resources}),[flow,elements,resources]);const knownKeys=useMemo(()=>new Set(elementKeys),[elementKeys])
 const ask=async()=>{setBusy(true);setProposal(null);setErrors([]);try{const instruction={draft:'Draft a metadata-only Flow change proposal',evolve:'Evolve this Flow metadata',summarize:`Summarize this Flow at ${length} length`,formula:'Help write or correct a Flow formula',test:'Generate a Flow Test Mode scenario with inputs and assertions',troubleshoot:'Troubleshoot this Flow and propose metadata fixes',integration:'Recommend metadata/connector changes for this integration Flow'}[mode];const r=await apiRequest('/api/jarvis',{method:'POST',body:{message:`You are OneEngine Flow Assistant. Never emit business-specific source code. ${instruction}. Return concise explanation and when changing Builder state JSON with {elements,resources,start,testScenario}. Only use these element keys: ${[...knownKeys].join(', ')}. Request: ${prompt}\nMetadata: ${JSON.stringify(context)}`}});const text=r?.data?.answer||'';setAnswer(text);const parsed=extractJson(text);if(parsed){const nextErrors=validateProposal(parsed,knownKeys);setErrors(nextErrors);if(!nextErrors.length)setProposal(parsed)}}catch(e){setErrors([e.message||'AI assistance unavailable'])}finally{setBusy(false)}}
 return <aside className="gptb-edit-history gptb-ai-assistant"><header><div><strong>Flow Assistant</strong><small>AI changes require validation and confirmation.</small></div><button className="gptb-icon-button" onClick={onClose}>×</button></header><div className="gptb-ai-tabs">{[['draft','Draft'],['evolve','Evolve'],['summarize','Summarize'],['formula','Formula'],['test','Test Scenario'],['troubleshoot','Troubleshoot'],['integration','Integration']].map(([k,l])=><button key={k} className={mode===k?'is-active':''} onClick={()=>setMode(k)}>{l}</button>)}</div>{mode==='summarize'?<select value={length} onChange={e=>setLength(e.target.value)}><option value="short">Short</option><option value="standard">Standard</option><option value="long">Long</option></select>:null}<textarea rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe what the assistant should do…"/><button className="gptb-button is-brand" disabled={busy||!prompt.trim()} onClick={ask}>{busy?'Working…':'Generate'}</button>{errors.length?<div className="gptb-gr-errors">{errors.map(e=><span key={e}>{e}</span>)}</div>:null}{answer?<section className="gptb-ai-result"><pre>{answer}</pre>{proposal?<div><b>Validated Builder Changes</b><p>Review before applying. You can undo the applied change from Builder Undo.</p>{mode==='test'&&proposal.testScenario?<button className="gptb-button" onClick={()=>onGenerateTest?.(proposal.testScenario)}>Add Test Scenario</button>:null}<button className="gptb-button is-brand" onClick={()=>onApply?.(proposal)}>Apply Changes</button></div>:null}</section>:null}</aside>
}
