import { useEffect, useMemo, useState } from 'react'
import { apiRequest } from '../../../services/api'

export function orchestrationDefaults(key){
  if(key==='orchestration_stage')return{stepMode:'sequential',entryMode:'all',entryFormula:'',exitMode:'all',exitFormula:'',evaluationFlowId:'',nextStage:'next'}
  if(key==='orchestration_interactive_step')return{assignmentType:'user',assignmentId:'',screenFlowId:'',evaluationFlowId:'',runAs:'current_user',dueHours:0,resumable:true,completionMode:'completed'}
  return{automationType:'flow',flowId:'',actionKey:'',evaluationFlowId:'',runAs:'system',faultBehavior:'fault_path',resumable:true}
}
export function orchestrationErrors(key,c={}){
  const errors=[]
  if(key==='orchestration_interactive_step'){if(!c.assignmentId)errors.push('Select an assignee.');if(!c.screenFlowId)errors.push('Select a Screen Flow.')}
  if(key==='orchestration_background_step'&&c.automationType==='flow'&&!c.flowId)errors.push('Select an autolaunched flow.')
  if(key==='orchestration_background_step'&&c.automationType==='action'&&!c.actionKey)errors.push('Select an action.')
  return errors
}
export function orchestrationRuntimeElement(instance){return{id:instance.id,key:instance.key,label:instance.label,apiName:instance.apiName,description:instance.description||'',...orchestrationDefaults(instance.key),...(instance.config||{})}}
export default function GPTBuilderOrchestrationElement({draft,updateConfig,onConfiguredChange}){
 const c={...orchestrationDefaults(draft.key),...(draft.config||{})},[users,setUsers]=useState([]),[groups,setGroups]=useState([]),[flows,setFlows]=useState([]),[actions,setActions]=useState([])
 useEffect(()=>{let live=true;Promise.all([apiRequest('/api/platform/approval-users').catch(()=>({data:[]})),apiRequest('/api/platform/approval-groups').catch(()=>({data:[]})),apiRequest('/api/platform/rules').catch(()=>({data:[]})),apiRequest('/api/platform/workflow-actions').catch(()=>({data:[]}))]).then(([u,g,f,a])=>{if(live){setUsers(u?.data||[]);setGroups(g?.data||[]);setFlows(f?.data||[]);setActions(a?.data||[])}});return()=>{live=false}},[])
 const errors=useMemo(()=>orchestrationErrors(draft.key,c),[draft.key,JSON.stringify(c)]);useEffect(()=>onConfiguredChange?.(!errors.length,errors),[JSON.stringify(errors)]);const patch=x=>updateConfig({...c,...x})
 const evaluation=<label><span>Evaluation Flow</span><select value={c.evaluationFlowId||''} onChange={e=>patch({evaluationFlowId:e.target.value})}><option value="">None</option>{flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
 if(draft.key==='orchestration_stage')return <div className="gptb-gr"><section><h3>Stage</h3><label><span>Step Execution</span><select value={c.stepMode} onChange={e=>patch({stepMode:e.target.value})}><option value="sequential">Sequential</option><option value="concurrent">Concurrent</option></select></label>{evaluation}<label><span>Entry Requirements</span><select value={c.entryMode} onChange={e=>patch({entryMode:e.target.value})}><option value="all">All Conditions Are Met</option><option value="any">Any Condition Is Met</option><option value="formula">Formula Evaluates to True</option></select></label><label><span>Entry Formula</span><input value={c.entryFormula||''} onChange={e=>patch({entryFormula:e.target.value})}/></label><label><span>Exit Requirements</span><select value={c.exitMode} onChange={e=>patch({exitMode:e.target.value})}><option value="all">All Conditions Are Met</option><option value="any">Any Condition Is Met</option><option value="formula">Formula Evaluates to True</option></select></label><label><span>Exit Formula</span><input value={c.exitFormula||''} onChange={e=>patch({exitFormula:e.target.value})}/></label><label><span>Stage Transition</span><select value={c.nextStage} onChange={e=>patch({nextStage:e.target.value})}><option value="next">Next Stage</option><option value="goto">Go To Stage</option><option value="end">End Orchestration</option></select></label>{c.nextStage==='goto'?<label><span>Go To Stage API Name</span><input value={c.goToStage||''} onChange={e=>patch({goToStage:e.target.value})}/></label>:null}</section></div>
 if(draft.key==='orchestration_interactive_step'){const targets=c.assignmentType==='group'?groups:users;return <div className="gptb-gr"><section><h3>Interactive Step</h3><label><span>Assignee Type</span><select value={c.assignmentType} onChange={e=>patch({assignmentType:e.target.value,assignmentId:''})}><option value="user">User</option><option value="group">Group / Queue</option></select></label><label><span>Assignee <b>*</b></span><select value={c.assignmentId} onChange={e=>patch({assignmentId:e.target.value})}><option value="">Select assignee</option>{targets.map(x=><option key={x.id} value={x.id}>{x.name||x.label||x.email||x.id}</option>)}</select></label><label><span>Screen Flow <b>*</b></span><select value={c.screenFlowId||''} onChange={e=>patch({screenFlowId:e.target.value})}><option value="">Select Screen Flow</option>{flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{evaluation}<label><span>Due In (Hours)</span><input type="number" min="0" value={c.dueHours||0} onChange={e=>patch({dueHours:Number(e.target.value)})}/></label><label><span>Run As</span><select value={c.runAs} onChange={e=>patch({runAs:e.target.value})}><option value="current_user">Current User</option><option value="system">System Context</option></select></label><label><input type="checkbox" checked={c.resumable!==false} onChange={e=>patch({resumable:e.target.checked})}/><span>Resume orchestration when work item completes</span></label></section>{errors.length?<div className="gptb-gr-errors">{errors.map(e=><span key={e}>{e}</span>)}</div>:null}</div>}
 return <div className="gptb-gr"><section><h3>Background Step</h3><label><span>Automation</span><select value={c.automationType} onChange={e=>patch({automationType:e.target.value})}><option value="flow">Autolaunched Flow</option><option value="action">Action</option></select></label>{c.automationType==='flow'?<label><span>Flow <b>*</b></span><select value={c.flowId||''} onChange={e=>patch({flowId:e.target.value})}><option value="">Select flow</option>{flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>:<label><span>Action <b>*</b></span><select value={c.actionKey||''} onChange={e=>patch({actionKey:e.target.value})}><option value="">Select action</option>{actions.map(a=><option key={a.key} value={a.key}>{a.displayName||a.key}</option>)}</select></label>}{evaluation}<label><span>Run As</span><select value={c.runAs} onChange={e=>patch({runAs:e.target.value})}><option value="system">System Context</option><option value="current_user">Current User</option></select></label><label><span>On Error</span><select value={c.faultBehavior} onChange={e=>patch({faultBehavior:e.target.value})}><option value="fault_path">Follow Fault Path</option><option value="stop">Stop Orchestration</option></select></label><label><input type="checkbox" checked={c.resumable!==false} onChange={e=>patch({resumable:e.target.checked})}/><span>Persist and resume this step</span></label></section>{errors.length?<div className="gptb-gr-errors">{errors.map(e=><span key={e}>{e}</span>)}</div>:null}</div>
}
