import { useEffect, useMemo, useState } from 'react'
import { apiRequest } from '../../../services/api'

function duration(run){const a=new Date(run.started_at||0).getTime(),b=new Date(run.completed_at||0).getTime();return a&&b&&b>=a?b-a:Number(run.metadata?.durationMs||0)}
function within(run,range){if(range==='all')return true;const days=range==='7d'?7:range==='30d'?30:90;return new Date(run.started_at||run.created_at||0).getTime()>=Date.now()-days*86400000}
export default function GPTBuilderMonitoringPanel({workflowId,elements=[],onClose,onNavigateElement}){
 const [runs,setRuns]=useState([]),[range,setRange]=useState('30d'),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;setLoading(true);apiRequest('/api/platform/workflow-runs?limit=500').then(r=>{if(live)setRuns((r?.data||[]).filter(x=>String(x.workflow_id)===String(workflowId)))}).finally(()=>live&&setLoading(false));return()=>{live=false}},[workflowId])
 const filtered=useMemo(()=>runs.filter(r=>within(r,range)),[runs,range])
 const stats=useMemo(()=>{const completed=filtered.filter(r=>r.status==='COMPLETED'),failed=filtered.filter(r=>r.status==='FAILED'),waiting=filtered.filter(r=>['WAITING','PENDING','RUNNING'].includes(r.status));const ds=filtered.map(duration).filter(Boolean);return{total:filtered.length,avg:ds.length?Math.round(ds.reduce((a,b)=>a+b,0)/ds.length):0,completed:completed.length,failed:failed.length,waiting:waiting.length}},[filtered])
 const elementStats=useMemo(()=>{const map=new Map(elements.map(e=>[String(e.id),{element:e,runs:0,failed:0,totalMs:0}]));for(const run of filtered){for(const step of run.metadata?.steps||[]){const id=String(step.stepId||step.step_identifier||'').split('@')[0],row=map.get(id);if(row){row.runs++;if(step.status==='FAILED')row.failed++;row.totalMs+=Number(step.duration_ms||0)}}}return [...map.values()]},[filtered,elements])
 const open=async(run)=>{setSelected(run.id);try{const r=await apiRequest(`/api/platform/workflow-runs/${encodeURIComponent(run.id)}`);setDetail(r?.data||null)}catch{setDetail({run})}}
 return <aside className="gptb-edit-history gptb-monitoring" aria-label="Flow Monitoring">
  <header><div><span><strong>Flow Monitoring</strong><small>Runs, performance, failures and dependencies.</small></span></div><button className="gptb-icon-button" onClick={onClose}>×</button></header>
  <div className="gptb-compare-selectors"><label><span>Date Range</span><select value={range} onChange={e=>setRange(e.target.value)}><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="90d">Last 90 Days</option><option value="all">All Time</option></select></label></div>
  <div className="gptb-monitor-cards"><div><b>{stats.total}</b><span>Total Runs</span></div><div><b>{stats.avg} ms</b><span>Average Duration</span></div><div><b>{stats.failed}</b><span>Failed</span></div><div><b>{stats.waiting}</b><span>Paused / Waiting</span></div></div>
  <section className="gptb-monitor-section"><h4>Run Status</h4><p>Completed {stats.completed} · Failed {stats.failed} · Waiting/Running {stats.waiting}</p></section>
  <section className="gptb-monitor-section"><h4>Element Analytics</h4>{elementStats.map(row=><button key={row.element.id} type="button" className="gptb-monitor-row" onClick={()=>onNavigateElement?.(row.element.id)}><span><b>{row.element.label||row.element.apiName}</b><small>{row.element.key}</small></span><span>{row.runs} runs · {row.failed} failed · {row.runs?Math.round(row.totalMs/row.runs):0} ms avg</span></button>)}</section>
  <section className="gptb-monitor-section"><h4>Runs</h4>{loading?<p>Loading…</p>:filtered.map(run=><button key={run.id} type="button" className={selected===run.id?'gptb-monitor-row is-active':'gptb-monitor-row'} onClick={()=>open(run)}><span><b>{run.status}</b><small>{new Date(run.started_at||run.created_at).toLocaleString()}</small></span><span>{duration(run)} ms</span></button>)}</section>
  {detail?.run?<section className="gptb-monitor-section"><h4>Open Details</h4><pre>{JSON.stringify({status:detail.run.status,error:detail.run.error_text,record:detail.run.record_id,trigger:detail.run.trigger_key,steps:detail.steps||[],scheduled:(detail.steps||[]).filter(s=>s.job_next_attempt_at)},null,2)}</pre></section>:null}
  <section className="gptb-monitor-section"><h4>Dependencies & Usage</h4><p>{elements.filter(e=>['subflow','action','screen','orchestration_interactive_step','approval_step'].includes(e.key)).length} referenced Flow/Action/Screen dependencies in this version.</p>{elements.filter(e=>['subflow','action','screen','orchestration_interactive_step','approval_step'].includes(e.key)).map(e=><button key={e.id} className="gptb-monitor-row" onClick={()=>onNavigateElement?.(e.id)}><span><b>{e.label||e.apiName}</b><small>{e.key}</small></span><span>Used by this Flow</span></button>)}</section>
 </aside>
}
