import { useMemo, useState } from 'react'
import { apiRequest } from '../../../services/api'

function extractJson(text){const raw=String(text||'');const fenced=raw.match(/\`\`\`(?:json)?\s*([\s\S]*?)\`\`\`/i)?.[1]||raw;const a=fenced.indexOf('{'),b=fenced.lastIndexOf('}');if(a<0||b<a)return null;try{return JSON.parse(fenced.slice(a,b+1))}catch{return null}}
export default function GPTBuilderAIAssistant({flow,elements,resources,onApply,onClose,onGenerateTest}){
 const [mode,setMode]=useState('draft'),[prompt,setPrompt]=useState(''),[length,setLength]=useState('standard'),[busy,setBusy]=useState(false),[answer,setAnswer]=useState(''),[proposal,setProposal]=useState(null)
 const context=useMemo(()=>({flow:{key:flow?.key,label:flow?.label,start:flow?.start},elements:elements.map(e=>({id:e.id,key:e.key,label:e.label,apiName:e.apiName,config:e.config})),resources}),[flow,elements,resources])
 const ask=async()=>{setBusy(true);setProposal(null);try{const instruction=mode==='draft'?'Draft a valid metadata-only Flow change proposal':mode==='evolve'?'Evolve this Flow from its current metadata':mode==='summarize'?\`Summarize this Flow at ${length} length\`:mode==='formula'?'Help write or correct a Flow formula':mode==='test'?'Generate a Flow Test Mode scenario with inputs and assertions':mode==='troubleshoot'?'Troubleshoot this Flow and identify likely configuration/runtime faults':'Recommend the metadata/connector changes needed for this integration Flow';const message=\`You are OneEngine GPT Builder assistant. Never emit business-specific source code. ${instruction}. Return concise explanation and, when proposing Builder changes, JSON with {elements,resources,start,testScenario}. User request: ${prompt}\nCurrent Flow metadata: ${JSON.stringify(context)}\`;const r=await apiRequest('/api/jarvis',{method:'POST',body:{message}});const text=r?.data?.answer||'';setAnswer(text);setProposal(extractJson(text))}catch(e){setAnswer(e.message||'AI assistance unavailable')}finally{setBusy(false)}}
 return <aside className="gptb-edit-history gptb-ai-assistant" aria-label="Flow Assistant"><header><div><span><strong>Flow Assistant</strong><small>Draft, evolve, explain, test and troubleshoot with confirmation.</small></span></div><button className="gptb-icon-button" onClick={onClose}>×</button></header><div className="gptb-ai-tabs">{[['draft','Draft'],['evolve','Evolve'],['summarize','Summarize'],['formula','Formula'],['test','Test Scenario'],['troubleshoot','Troubleshoot'],['integration','Integration']].map(([key,label])=><button key={key} className={mode===key?'is-active':''} onClick={()=>setMode(key)}>{label}</button>)}</div>{mode==='summarize'?<label><span>Summary Length</span><select value={length} onChange={e=>setLength(e.target.value)}><option value="short">Short</option><option value="standard">Standard</option><option value="long">Long</option></select></label>:null}<label><span>What should the assistant do?</span><textarea rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the automation, change, formula, test, problem, or integration…"/></label><button className="gptb-button is-brand" disabled={busy||!prompt.trim()} onClick={ask}>{busy?'Working…':'Generate'}</button>{answer?<section className="gptb-ai-result"><h4>Assistant Response</h4><pre>{answer}</pre>{proposal?<div className="gptb-ai-confirm"><b>Proposed Builder Changes</b><p>Review before applying. The assistant never changes the Flow automatically.</p>{mode==='test'&&proposal.testScenario?<button className="gptb-button" onClick={()=>onGenerateTest?.(proposal.testScenario)}>Add Test Scenario</button>:null}<button className="gptb-button is-brand" onClick={()=>onApply?.(proposal)}>Apply Changes</button></div>:null}</section>:null}</aside>
}
