import {Database,GitBranch,MoreVertical,Plus,Trash2,Copy,Zap,ZoomIn,ZoomOut,Play,Square} from 'lucide-react'
export default function Builder3Canvas({nodes,edges,selected,onSelect,onInsert,onDelete,onCopy,onStart,startConfig,zoom,onZoom}) {
  const claimed=new Set(edges.filter(e=>['DECISION','LOOP'].includes(nodes.find(n=>n.id===e.source)?.type)&&e.sourceHandle&&e.sourceHandle!=='normal').map(e=>e.target))
  const trunks=nodes.filter(n=>!claimed.has(n.id))
  const add=(index,branch=null)=><><button className="b3-add" aria-label={branch?`Add to ${branch.label}`:index<nodes.length?`Insert before ${nodes[index].label}`:'Add element at end'} onClick={()=>onInsert(index,branch)}><Plus size={14}/></button><div className="b3-line"/></>
  function renderNode(node,path=new Set()) {
    if(path.has(node.id))return <p className="b3-error">Circular connection</p>
    const nextPath=new Set([...path,node.id])
    const branches=node.type==='DECISION'?[...(node.config?.outcomes||[]).map(o=>({id:o.id,label:o.label})),{id:'default',label:node.config?.defaultOutcomeLabel||'Default Outcome'}]:node.type==='LOOP'?[{id:'body',label:'For Each'},{id:'after',label:'After Last'}]:[]
    return <div className="b3-tree-node" key={node.id}><div className="b3-node-row"><button data-node-id={node.id} data-kind={['ACTION','SCREEN','SUBFLOW'].includes(node.type)?'Interaction':['GET_RECORDS','CREATE_RECORDS','UPDATE_RECORDS','DELETE_RECORDS'].includes(node.type)?'Data':'Logic'} className={`b3-node ${selected===node.id?'is-selected':''}`} onClick={()=>onSelect(node)}><span className="b3-node-icon">{node.type==='DECISION'?<GitBranch size={16}/>:node.type==='ACTION'?<Zap size={16}/>:<Database size={16}/>}</span><span><b>{node.label}</b><small>{node.type.replaceAll('_',' ')}</small></span></button><details className="b3-canvas-menu"><summary aria-label={`Menu for ${node.label}`}><MoreVertical size={16}/></summary><div><button onClick={()=>onCopy(node.id)}><Copy size={14}/> Copy Element</button><button onClick={()=>onDelete(node.id)}><Trash2 size={14}/> Delete Element</button></div></details></div><div className="b3-line"/>{branches.length?<div className="b3-branches">{branches.map(branch=><section className="b3-branch" key={branch.id}><span className="b3-branch-label">{branch.label}</span><div className="b3-line"/>{edges.filter(e=>e.source===node.id&&e.sourceHandle===branch.id).map(e=>nodes.find(n=>n.id===e.target)).filter(Boolean).map(child=>renderNode(child,nextPath))}{add(nodes.length,{source:node.id,handle:branch.id,label:branch.label})}</section>)}</div>:null}</div>
  }
  return <main className="b3-canvas"><div className="b3-zoom"><button aria-label="Zoom out" onClick={()=>onZoom(Math.max(50,zoom-10))}><ZoomOut size={14}/></button><span>{zoom}%</span><button aria-label="Zoom in" onClick={()=>onZoom(Math.min(150,zoom+10))}><ZoomIn size={14}/></button><button aria-label="Reset zoom" onClick={()=>onZoom(100)}>↺</button></div><div className="b3-flow" style={{zoom:zoom/100}}><button className="b3-start" onClick={onStart}><span className="b3-terminal-icon"><Play size={18} fill="currentColor"/></span><span>Start</span><small>{startConfig.objectKey?`${startConfig.objectKey} · ${String(startConfig.trigger||'').replaceAll('_',' ')}`:'Configure Trigger'}</small></button><div className="b3-line"/>{trunks.map(node=><div className="b3-step-wrap" key={node.id}>{add(nodes.indexOf(node))}{renderNode(node)}</div>)}{add(nodes.length)}<div className="b3-end"><span className="b3-terminal-icon"><Square size={15} fill="currentColor"/></span><b>End</b></div></div></main>
}
