import { useEffect, useState } from 'react'
import { Search, Plus, X, ChevronLeft, Workflow } from 'lucide-react'
import { apiRequest } from '../../services/api'
import Builder3Editor from './Builder3Editor'
import { FLOW_TYPES } from './builder3Model'
import './Builder3Page.css'

export default function Builder3Page({initialWorkflowId='',onWorkflowOpen,onWorkflowClose}) {
  const [flows,setFlows]=useState([]),[objects,setObjects]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[chooser,setChooser]=useState(false),[type,setType]=useState(''),[object,setObject]=useState(''),[objectQuery,setObjectQuery]=useState(''),[objectOpen,setObjectOpen]=useState(false),[editing,setEditing]=useState(initialWorkflowId?{id:initialWorkflowId}:null)
  const refresh=()=>{setLoading(true);Promise.all([apiRequest('/api/platform/rules'),apiRequest('/api/platform/objects')]).then(([f,o])=>{setFlows(Array.isArray(f.data)?f.data:[]);setObjects(o.data?.objects||o.data||[]);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
  useEffect(refresh,[])
  const close=()=>{setEditing(null);onWorkflowClose?.();refresh()}
  if(editing)return <Builder3Editor initialWorkflowId={editing.id||''} initialFlowType={editing.type||''} initialObjectKey={editing.object||''} onClose={close} onSaved={saved=>onWorkflowOpen?.(saved.id)}/>
  const matches=objects.filter(o=>`${o.label||o.name} ${o.object_key||o.api_name}`.toLowerCase().includes(objectQuery.toLowerCase()))
  return <div className="b3-library"><header><div><Workflow size={24}/><h2>Builder 3</h2></div><button className="is-primary" onClick={()=>{setType('');setObject('');setObjectQuery('');setChooser(true)}}><Plus size={16}/> New Flow</button></header><label className="b3-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search flows…"/></label>{error?<p role="alert" className="b3-error">{error}</p>:null}{loading?<p>Loading flows…</p>:<table><thead><tr><th>Flow Label</th><th>Flow Type</th><th>Status</th><th>Version</th></tr></thead><tbody>{flows.filter(f=>f.action?.builder3).filter(f=>String(f.name).toLowerCase().includes(query.toLowerCase())).map(f=><tr key={f.id}><td><button className="b3-text-action" onClick={()=>{setEditing({id:f.id});onWorkflowOpen?.(f.id)}}>{f.name}</button></td><td>{FLOW_TYPES[f.action?.flowType]?.label||f.trigger_key}</td><td>{f.runtime_active||f.active?'Active':'Draft'}</td><td>{f.version||1}</td></tr>)}</tbody></table>}
    {chooser?<div className="b3-modal-backdrop"><section className="b3-modal b3-type-modal" role="dialog" aria-modal="true" aria-label="New Flow"><header><div><h3>New Flow</h3><p>Select a Flow Type</p></div><button aria-label="Close New Flow" onClick={()=>setChooser(false)}><X size={18}/></button></header><div className="b3-type-body"><h4>Frequently Used</h4><div className="b3-type-grid">{Object.entries(FLOW_TYPES).map(([key,flow])=><button className={type===key?'is-selected':''} key={key} onClick={()=>{setType(key);setObject('');setObjectQuery('')}}><Workflow size={22}/><b>{flow.label}</b><small>{key==='record'?'Runs when a record is created, updated, or deleted.':key==='schedule'?'Runs at the date, time, and frequency you choose.':key==='screen'?'Guides users through interactive screens.':key==='autolaunched'?'Starts from another flow, action, or API.':'Uses the OneEngine flow runtime.'}</small></button>)}</div>{type==='record'?<div className="b3-form"><label>Object <span className="b3-required">*</span><div className="b3-object-picker"><Search size={15}/><input role="combobox" aria-label="Search objects" aria-expanded={objectOpen} value={objectQuery} onFocus={()=>setObjectOpen(true)} onChange={e=>{setObjectQuery(e.target.value);setObject('');setObjectOpen(true)}} placeholder="Search objects…" onKeyDown={e=>{if(e.key==='Escape')setObjectOpen(false);if(e.key==='Enter'&&matches[0]){const o=matches[0];setObject(o.object_key||o.api_name||o.id);setObjectQuery(o.label||o.name);setObjectOpen(false)}}}/>{objectOpen?<div className="b3-object-picker-menu" role="listbox">{matches.map(o=><button key={o.id} role="option" aria-selected={object===String(o.object_key||o.api_name||o.id)} onClick={()=>{setObject(o.object_key||o.api_name||o.id);setObjectQuery(o.label||o.name);setObjectOpen(false)}}><span>{o.label||o.name}</span><small>{o.object_key||o.api_name}</small></button>)}{!matches.length?<p>No matching objects</p>:null}</div>:null}</div></label><p className="b3-help">Choose the object whose record changes trigger this flow.</p></div>:null}</div><footer><button onClick={()=>setChooser(false)}><ChevronLeft size={14}/> Cancel</button><button className="is-primary" disabled={!type||(type==='record'&&!object)} onClick={()=>{setEditing({type,object});setChooser(false)}}>Create</button></footer></section></div>:null}
  </div>
}
