export function ResponsiveLayoutMode({ value="desktop", onChange }) {
  return <div className="inline-flex rounded-lg border p-1" style={{borderColor:"var(--onepos-border)",background:"var(--onepos-surface-alt)"}}>{[["desktop","Desktop"],["tablet","Tablet"],["mobile","Mobile"]].map(([key,label])=><button key={key} type="button" className={`rounded-md px-3 py-1.5 text-xs font-medium ${value===key?"shadow-sm":""}`} style={value===key?{background:"var(--onepos-surface-raised)",color:"var(--onepos-text-heading)"}:{color:"var(--onepos-text-muted)"}} onClick={()=>onChange?.(key)}>{label}</button>)}</div>;
}

export function DashboardRunAsEditor({ mode="VIEWER", userId="", users=[], onChange }) {
  return <div className="grid gap-3 md:grid-cols-2"><label className="onepos-label">Run dashboard as<select className="onepos-input mt-1" value={mode} onChange={(e)=>onChange?.({mode:e.target.value,userId:e.target.value==="VIEWER"?null:userId})}><option value="VIEWER">Dashboard viewer</option><option value="FIXED_USER">Specified user</option></select></label>{mode==="FIXED_USER"?<label className="onepos-label">Run-as user<select className="onepos-input mt-1" value={userId||""} onChange={(e)=>onChange?.({mode,userId:e.target.value})}><option value="">Select user</option>{users.map((user)=><option key={user.id} value={user.id}>{user.full_name||user.username}</option>)}</select></label>:null}</div>;
}

const componentReportFields=(component)=>{
  const definition=component?.reportDefinition||component?.config?.resolvedReport||null;
  if(!definition)return [];
  const keys=[...(definition.fields||[]),...(definition.rowGroups||definition.groupBy||[]),...(definition.columnGroups||[])];
  const summaries=(definition.summaries||[]).map((summary)=>summary.alias||`${String(summary.aggregate||"count").toLowerCase()}_${summary.field}`);
  return [...new Set([...keys,...summaries].map(String).filter(Boolean))];
};

export function DashboardFilterEditor({ filters=[], components=[], onChange }) {
  const update=(index,patch)=>onChange(filters.map((filter,i)=>i===index?{...filter,...patch}:filter));
  return <fieldset className="rounded-xl border p-3 space-y-3" style={{borderColor:"var(--onepos-border)"}}><div className="flex items-center justify-between"><legend className="text-sm font-medium">Dashboard filters <span className="font-normal opacity-70">({filters.length}/5)</span></legend>{filters.length<5?<button type="button" className="onepos-btn onepos-btn-sm onepos-btn-secondary" onClick={()=>onChange([...filters,{key:`filter_${filters.length+1}`,label:`Filter ${filters.length+1}`,type:"select",allowAll:true,options:[],mappings:[]}])}>Add filter</button>:null}</div>
    {filters.map((filter,index)=><div key={filter.key||index} className="rounded-lg border p-3 space-y-2" style={{borderColor:"var(--onepos-border)"}}><div className="grid gap-2 md:grid-cols-3"><label className="onepos-label">Label<input className="onepos-input mt-1" value={filter.label||""} onChange={(e)=>update(index,{label:e.target.value})}/></label><label className="onepos-label">Type<select className="onepos-input mt-1" value={filter.type||"select"} onChange={(e)=>update(index,{type:e.target.value})}><option value="select">Select</option><option value="multi_select">Multi select</option><option value="date">Date</option><option value="number">Number</option><option value="boolean">Boolean</option></select></label><label className="onepos-label">Options<input className="onepos-input mt-1" disabled={["date","number","boolean"].includes(filter.type)} value={(filter.options||[]).map((o)=>o.label??o.value??o).join(", ")} onChange={(e)=>update(index,{options:e.target.value.split(",").map((v)=>v.trim()).filter(Boolean).slice(0,50).map((v)=>({value:v,label:v}))})}/></label></div>
      {(filter.mappings||[]).map((mapping,mappingIndex)=><div key={mappingIndex} className="grid gap-2 md:grid-cols-[1fr_1fr_140px_auto]"><select className="onepos-input" value={mapping.componentId||""} onChange={(e)=>update(index,{mappings:filter.mappings.map((m,i)=>i===mappingIndex?{...m,componentId:e.target.value}:m)})}><option value="">All compatible components</option>{components.map((component)=><option key={component.id} value={component.id}>{component.title||component.type}</option>)}</select><select className="onepos-input" value={mapping.reportField||""} onChange={(e)=>update(index,{mappings:filter.mappings.map((m,i)=>i===mappingIndex?{...m,reportField:e.target.value}:m)})}><option value="">Select report field</option>{[...new Set((mapping.componentId?components.filter((component)=>String(component.id)===String(mapping.componentId)):components).flatMap(componentReportFields))].map((field)=><option key={field} value={field}>{field}</option>)}</select><select className="onepos-input" value={mapping.operator||"equals"} onChange={(e)=>update(index,{mappings:filter.mappings.map((m,i)=>i===mappingIndex?{...m,operator:e.target.value}:m)})}><option value="equals">Equals</option><option value="in">In</option><option value="gte">≥</option><option value="lte">≤</option></select><button type="button" className="onepos-btn onepos-btn-sm onepos-btn-secondary" onClick={()=>update(index,{mappings:filter.mappings.filter((_,i)=>i!==mappingIndex)})}>Remove</button></div>)}
      <div className="flex gap-2"><button type="button" className="onepos-btn onepos-btn-sm onepos-btn-secondary" onClick={()=>update(index,{mappings:[...(filter.mappings||[]),{componentId:"",reportField:"",operator:"equals"}]})}>Add mapping</button><button type="button" className="onepos-btn onepos-btn-sm onepos-btn-secondary" onClick={()=>onChange(filters.filter((_,i)=>i!==index))}>Delete filter</button></div>
    </div>)}
  </fieldset>;
}

export function responsiveComponents(components=[], layouts={}, mode="desktop") {
  const map=new Map((layouts?.[mode]||[]).map((entry)=>[String(entry.id),entry]));
  return components.map((component)=>{const override=map.get(String(component.id));return override?{...component,layout:{...component.layout,...override}}:component;});
}
