const CATALOG = [
  {
    key: "retail_pos",
    name: "POS & Sales",
    description: "Till sales, payments, returns and order processing.",
    route: "/app/sales",
    landingRoute: "/app",
    permissions: ["sale.view", "sale.create", "sale.refund"],
    storeScoped: true,
    category: "Operations",
  },
  {
    key: "receipt_qr",
    packageKey: "receipt_qr",
    name: "One Receipt QR",
    description: "Temporary PDF receipt downloads issued as a one-time QR token link from the till.",
    route: "/app/sales",
    permissions: ["sale.view", "sale.refund"],
    storeScoped: true,
    category: "Sales / Receipts",
    billable: false,
    licenceRequired: false,
    installable: true,
    visibility: "PUBLIC",
    iconAssetKey: "connect_printer",
    dependencies: ["retail_pos"],
  },
  {
    key: "products",
    name: "Products",
    description: "Product Core foundation for the canonical product catalogue and categories.",
    route: "/app/products",
    permissions: [
      "product.view", "product.create", "product.edit", "product.delete",
      "category.view", "category.create", "category.edit", "category.delete",
    ],
    storeScoped: false,
    category: "Catalogue & Supply",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    version: "1.1.0",
  },
  {
    key: "inventory",
    name: "Inventory",
    description: "Stock, replenishment and inventory movements.",
    route: "/app/objects/inventory_movement?appKey=inventory",
    permissions: ["inventory.view"],
    storeScoped: true,
    category: "Catalogue & Supply",
  },
  {
    key: "batch_expiry",
    name: "Batch & Expiry",
    description: "Batch stock, expiry tracking and FEFO inventory controls.",
    route: "/app/objects/inventory_batch?appKey=batch_expiry",
    permissions: ["inventory.view", "inventory.adjust"],
    storeScoped: true,
    category: "Catalogue & Supply",
  },
  {
    key: "hospitality",
    name: "Hospitality",
    description: "Floor plans, tables and reservations as an installable hospitality foundation.",
    route: "/app/integrations",
    permissions: [
      "hospitality.tables.view",
      "hospitality.tables.manage",
      "hospitality.floor.manage",
      "hospitality.reservations.view",
      "hospitality.reservations.manage",
      "hospitality.kds.view",
      "hospitality.kds.manage",
      "hospitality.kitchen.reprint",
      "hospitality.bill.split",
      "hospitality.table.transfer",
      "hospitality.service_charge.override",
      "hospitality.qr.manage",
    ],
    storeScoped: true,
    category: "Operations",
  },
  {
    key: "kds",
    name: "Kitchen Display",
    description: "Kitchen tickets and preparation status, licensed independently from core EPOS.",
    route: "/app/integrations",
    permissions: ["hospitality.kds.view", "hospitality.kds.manage", "hospitality.kitchen.reprint"],
    storeScoped: true,
    category: "Operations",
  },
  {
    key: "customer_credit",
    name: "Customer Credit",
    description: "Customer credit accounts, protected ledger transactions and credit controls.",
    route: "/app/customers",
    permissions: ["customer.credit.view", "customer.credit.manage"],
    storeScoped: true,
    category: "Business",
  },
  {
    key: "customers",
    name: "Customers",
    description: "Customer records, loyalty and customer activity.",
    route: "/app/customers",
    permissions: ["customer.view"],
    storeScoped: false,
    category: "Business",
  },
  {
    key: "loyalty",
    name: "Loyalty Core",
    description: "Canonical loyalty configuration, balances, activity and rules.",
    route: "/app/customers",
    permissions: ["customer.view", "loyalty.adjust", "settings.manage"],
    storeScoped: false,
    category: "Foundation",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    visibility: "HIDDEN",
    systemOnly: true,
  },
  {
    key: "suppliers",
    name: "Suppliers",
    description: "Supplier records, purchasing and supplier accounts.",
    route: "/app/suppliers",
    permissions: ["inventory.view", "purchase.view"],
    storeScoped: false,
    category: "Catalogue & Supply",
  },
  {
    key: "finance_core",
    packageKey: "finance_core",
    name: "Finance Core",
    description: "Hidden financial ledger and supplier-accounting foundation.",
    route: "/app/suppliers",
    permissions: ["purchase.view", "purchase.edit", "inventory.adjust", "reports.payments.view"],
    storeScoped: false,
    category: "Foundation",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    visibility: "HIDDEN",
    systemOnly: true,
    installable: true,
    dependencies: ["supplier_core"],
    bootstrapFoundation: true,
    capabilities: ["supplier_accounting", "financial_ledger"],
  },
  {
    key: "supplier_core",
    packageKey: "supplier_core",
    name: "Supplier Core",
    description: "Canonical supplier identity and supplier-product sourcing metadata.",
    route: "/app/suppliers",
    permissions: ["inventory.view", "inventory.adjust", "purchase.view"],
    storeScoped: false,
    category: "Catalogue & Supply",
    packageType: "FOUNDATION",
    technical: true,
    visibility: "HIDDEN",
    billable: false,
    systemOnly: true,
    installable: true,
    dependencies: ["products"],
  },
  {
    key: "purchasing_core",
    packageKey: "purchasing_core",
    name: "Purchasing Core",
    description: "Protected purchase, receipt and supplier-return transactions exposed through metadata.",
    route: "/app/purchases",
    permissions: ["purchase.view", "purchase.create", "purchase.edit", "inventory.adjust", "returns.create"],
    storeScoped: true,
    category: "Foundation",
    packageType: "FOUNDATION",
    technical: true,
    visibility: "HIDDEN",
    billable: false,
    systemOnly: true,
    installable: true,
    bootstrapFoundation: true,
    dependencies: ["supplier_core", "products", "inventory"],
    capabilities: ["purchasing", "purchase_receiving", "supplier_returns"],
  },
  {
    key: "staff",
    name: "Staff Core",
    description: "Reusable employee and attendance metadata over existing user identities.",
    route: "/app/employees",
    permissions: ["user.view", "user.create", "user.edit", "attendance.view", "attendance.use"],
    storeScoped: false,
    category: "Administration",
    packageType: "FOUNDATION",
    billable: false,
    version: "1.1.0",
  },
  {
    key: "reports",
    name: "Reports",
    description: "Operational, sales and configurable Platform reports.",
    route: "/app/reports",
    permissions: ["reports.summary.view", "reports.custom.view"],
    storeScoped: false,
    category: "Business",
  },
  {
    key: "online_orders",
    name: "Online Orders",
    description: "Provider-neutral online order records, fulfilment and lifecycle foundation.",
    route: "/app/order-prep",
    version: "1.0.0",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    visibility: "HIDDEN",
    systemOnly: true,
    dependencies: ["products", "inventory", { packageKey: "customers", optional: true }],
    permissions: ["online_orders.view", "online_orders.manage", "online_orders.status_update", "online_orders.cancel"],
    storeScoped: true,
    category: "Foundation",
  },
  {
    key: "integrations",
    name: "Integrations",
    description: "External delivery, payment and communication connections.",
    route: "/app/integrations",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    storeScoped: false,
    category: "Administration",
  },
  {
    key: "communication_core",
    packageKey: "communication_core",
    name: "Communication Core",
    description: "Provider-neutral communication events, templates, delivery tracking and workflow actions shared by Email, SMS and WhatsApp.",
    route: "/app/settings",
    permissions: ["communications.send", "integration.manage"],
    storeScoped: false,
    category: "Foundation",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    visibility: "HIDDEN",
    systemOnly: true,
    installable: true,
    dependencies: ["platform"],
    capabilities: [
      "communication_provider_metadata",
      "communication_templates",
      "communication_send",
      "communication_receive",
      "communication_delivery_events",
      "communication_workflow_triggers"
    ],
    communication: {
      channels: ["EMAIL", "SMS", "WHATSAPP", "IN_APP"],
      events: [
        "communication.message_received",
        "communication.message_sent",
        "communication.message_delivered",
        "communication.message_failed",
        "communication.opted_out",
        "communication.handoff"
      ],
      action: "SEND_COMMUNICATION",
      legacyActions: {
        EMAIL: "SEND_EMAIL",
        SMS: "SEND_SMS",
        WHATSAPP: "SEND_WHATSAPP",
        IN_APP: "IN_APP_NOTIFICATION"
      },
      providerMetadataSource: "integrations",
      templateSource: "platform_message_templates",
      deliverySource: "platform_communication_deliveries"
    }
  },

  {
    key: "connector_core",
    packageKey: "connector_core",
    name: "Connector Core",
    description: "Hidden runtime, capability routing and hardware-service contracts for installable connector apps.",
    route: "/app/integrations",
    permissions: ["connector.view", "connector.manage", "connector.test"],
    storeScoped: true,
    category: "Foundation",
    packageType: "FOUNDATION",
    technical: true,
    billable: false,
    visibility: "HIDDEN",
    systemOnly: true,
    installable: true,
    dependencies: [],
    capabilities: ["connector_runtime", "connector_capability_registry", "local_hardware_bridge_contract"],
  },
  {
    key: "payment_reference",
    packageKey: "payment_reference",
    name: "Reference Payment Connector (TEST)",
    description: "A payment simulator for connector setup and POS workflow testing. TEST ONLY; not a certified or production payment provider.",
    permissions: ["integration.manage", "sale.create", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Payment Connectors",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    iconAssetKey: "paypal",
    entitlementKey: "paypal_qr",
    connectorApp: {
      type: "payment",
      mode: "TEST",
      capabilities: [
        { key: "payment.sale", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.cancel", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.refund", requiredPermissions: ["sale.refund"] },
        { key: "payment.status", requiredPermissions: ["sale.view"] },
        { key: "payment.test", requiredPermissions: ["integration.manage"] },
        { key: "payment.health", requiredPermissions: ["connector.view"] },
      ],
      configurationSchema: [
        { key: "mode", type: "string", required: true, default: "TEST", enum: ["TEST"] },
        { key: "simulatedOutcome", type: "string", required: true, default: "APPROVED", enum: ["APPROVED", "DECLINED", "OFFLINE", "TIMEOUT", "ERROR"] },
      ],
    },
  },
  {
    key: "paypal_qr",
    packageKey: "paypal_qr",
    name: "PayPal QR Payment",
    description: "PayPal QR payment connector for transaction-specific QR payments using metadata-driven merchant configuration.",
    permissions: ["integration.manage", "sale.create", "sale.refund", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Payments / Integrations",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: {
      type: "payment",
      mode: "SANDBOX",
      paymentMethodCode: "paypal_qr",
      paymentMethodLabel: "PayPal QR",
      paymentMethodKind: "ONLINE",
      capabilities: [
        { key: "payment.sale", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.cancel", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.refund", requiredPermissions: ["sale.refund"] },
        { key: "payment.status", requiredPermissions: ["sale.view"] },
        { key: "payment.test", requiredPermissions: ["integration.manage"] },
        { key: "payment.health", requiredPermissions: ["connector.view"] },
      ],
      configurationSchema: [
        { key: "environment", type: "picklist", required: true, default: "DEMO", enum: ["DEMO", "SANDBOX", "LIVE"] },
        { key: "enabled", type: "boolean", default: false },
        { key: "displayName", type: "string", label: "Display name", default: "PayPal QR" },
        { key: "currency", type: "picklist", default: "GBP", enum: ["GBP", "USD", "EUR", "AUD", "CAD"] },
        { key: "clientId", type: "string", label: "Client ID", required: true },
        { key: "clientSecret", type: "secret", label: "Client secret", required: true },
        { key: "merchantId", type: "string", label: "Merchant ID" },
        { key: "webhookId", type: "string", label: "Webhook ID" },
        { key: "webhookSecret", type: "secret", label: "Webhook secret" },
        { key: "qrPaymentEnabled", type: "boolean", default: true, label: "QR payment enabled" },
        { key: "refundEnabled", type: "boolean", default: false, label: "Refund enabled" },
        { key: "paymentTimeoutSeconds", type: "number", default: 300 },
        { key: "pollingIntervalSeconds", type: "number", default: 5 },
        { key: "storeIds", type: "store lookup", label: "Store assignment" },
        { key: "tillIds", type: "till lookup", label: "Till assignment" },
        { key: "autoCloseSuccess", type: "boolean", default: true, label: "Auto close on success" },
        { key: "testConnection", type: "action", label: "Test connection" },
        { key: "connectionStatus", type: "readonly", label: "Connection status" },
      ],
    },
  },
  {
    key: "one_connect_google",
    packageKey: "one_connect_google",
    name: "Google Connect",
    description: "Licensed Google Workspace/OpenID Connect single sign-on for onePOS users with tenant-specific OAuth configuration.",
    route: "/app/google-connect",
    permissions: ["integration.manage"],
    storeScoped: false,
    category: "Identity & Access",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    entitlementKey: "google_sso",
    dependencies: ["connector_core"],
    iconAssetKey: "one-connect-google",
    capabilities: ["auth.google_sso", "auth.google_oauth_test"],
    providerConnector: {
      providerKey: "google",
      connectionMode: "OAUTH2",
      settingsRoute: "/app/google-connect",
    },
  },
  {
    key: "one_connect_dojo",
    packageKey: "one_connect_dojo",
    name: "One Connect - Dojo",
    description: "Dojo EPOS payment connector for POS card processing using a generic payment capability contract and metadata-managed device configuration.",
    permissions: ["integration.manage", "sale.create", "sale.refund", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Payment Connectors",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    iconAssetKey: "one_connect_dojo",
    connectorApp: {
      type: "payment",
      mode: "DEMO",
      provider: "dojo",
      paymentMethodCode: "dojo",
      paymentMethodLabel: "Dojo",
      paymentMethodKind: "TERMINAL",
      capabilities: [
        { key: "payment.sale", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.refund", requiredPermissions: ["sale.refund"] },
        { key: "payment.cancel", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.status", requiredPermissions: ["sale.view"] },
        { key: "payment.health", requiredPermissions: ["connector.view"] },
        { key: "payment.test", requiredPermissions: ["integration.manage"] },
      ],
      metadataSchema: {
        providerKey: "dojo",
        storeRelationship: true,
        tillRelationship: true,
        terminalIdentifier: true,
        liveMode: true,
        testMode: true,
        healthStatus: true,
      },
      configurationSchema: [
        { key: "enabled", type: "boolean", default: true },
        { key: "mode", type: "picklist", required: true, default: "DEMO", enum: ["DEMO", "SANDBOX", "LIVE"] },
        { key: "displayName", type: "string", label: "Display name", default: "Dojo" },
        { key: "accountId", type: "string", label: "Account ID" },
        { key: "apiKey", type: "secret", label: "API key" },
        { key: "apiSecret", type: "secret", label: "API secret" },
        { key: "terminalId", type: "string", label: "Terminal ID" },
        { key: "storeId", type: "store lookup", label: "Store assignment" },
        { key: "tillId", type: "till lookup", label: "Till assignment" },
        { key: "testConnection", type: "action", label: "Test connection" },
        { key: "healthStatus", type: "readonly", label: "Health status" },
      ],
    },
  },
  {
    key: "one_connect_sumup",
    packageKey: "one_connect_sumup",
    name: "One Connect - SumUp",
    description: "SumUp Terminal/Cloud connector for POS card processing using provider-neutral payment capabilities and store/till pairing metadata.",
    permissions: ["integration.manage", "sale.create", "sale.refund", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Payment Connectors",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    iconAssetKey: "one_connect_sumup",
    connectorApp: {
      type: "payment",
      mode: "DEMO",
      provider: "sumup",
      paymentMethodCode: "sumup",
      paymentMethodLabel: "SumUp",
      paymentMethodKind: "TERMINAL",
      capabilities: [
        { key: "payment.sale", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.refund", requiredPermissions: ["sale.refund"] },
        { key: "payment.cancel", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.status", requiredPermissions: ["sale.view"] },
        { key: "payment.health", requiredPermissions: ["connector.view"] },
        { key: "payment.test", requiredPermissions: ["integration.manage"] },
      ],
      metadataSchema: {
        providerKey: "sumup",
        storeRelationship: true,
        tillRelationship: true,
        terminalIdentifier: true,
        liveMode: true,
        testMode: true,
        healthStatus: true,
      },
      configurationSchema: [
        { key: "enabled", type: "boolean", default: true },
        { key: "mode", type: "picklist", required: true, default: "DEMO", enum: ["DEMO", "SANDBOX", "LIVE"] },
        { key: "displayName", type: "string", label: "Display name", default: "SumUp" },
        { key: "apiKey", type: "secret", label: "API key" },
        { key: "merchantId", type: "string", label: "Merchant ID" },
        { key: "readerId", type: "string", label: "Reader ID" },
        { key: "storeId", type: "store lookup", label: "Store assignment" },
        { key: "tillId", type: "till lookup", label: "Till assignment" },
        { key: "selfCheckoutSupported", type: "boolean", default: true, label: "Self Checkout supported" },
        { key: "testConnection", type: "action", label: "Test connection" },
        { key: "healthStatus", type: "readonly", label: "Health status" },
      ],
    },
  },
  {
    key: "one_connect_square",
    packageKey: "one_connect_square",
    name: "One Connect - Square",
    description: "Square Terminal API payment connector for POS and unattended device pairing using generic payment capabilities and terminal assignment metadata.",
    permissions: ["integration.manage", "sale.create", "sale.refund", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Payment Connectors",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    iconAssetKey: "one_connect_square",
    connectorApp: {
      type: "payment",
      mode: "DEMO",
      provider: "square",
      paymentMethodCode: "square",
      paymentMethodLabel: "Square",
      paymentMethodKind: "TERMINAL",
      capabilities: [
        { key: "payment.sale", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.refund", requiredPermissions: ["sale.refund"] },
        { key: "payment.cancel", selfCheckoutSupported: true, requiredPermissions: ["sale.create"] },
        { key: "payment.status", requiredPermissions: ["sale.view"] },
        { key: "payment.health", requiredPermissions: ["connector.view"] },
        { key: "payment.test", requiredPermissions: ["integration.manage"] },
      ],
      metadataSchema: {
        providerKey: "square",
        storeRelationship: true,
        tillRelationship: true,
        terminalIdentifier: true,
        liveMode: true,
        testMode: true,
        healthStatus: true,
      },
      configurationSchema: [
        { key: "enabled", type: "boolean", default: true },
        { key: "mode", type: "picklist", required: true, default: "DEMO", enum: ["DEMO", "SANDBOX", "LIVE"] },
        { key: "displayName", type: "string", label: "Display name", default: "Square" },
        { key: "applicationId", type: "string", label: "Application ID" },
        { key: "accessToken", type: "secret", label: "Access token" },
        { key: "locationId", type: "string", label: "Location ID" },
        { key: "deviceId", type: "string", label: "Device ID" },
        { key: "storeId", type: "store lookup", label: "Store assignment" },
        { key: "tillId", type: "till lookup", label: "Till assignment" },
        { key: "testConnection", type: "action", label: "Test connection" },
        { key: "healthStatus", type: "readonly", label: "Health status" },
      ],
    },
  },
  {
    key: "payment_connector_template",
    name: "Payment Connector Template",
    description: "Installable metadata template for a future payment connector; does not process payments by itself.",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    category: "Connector Templates",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: { type: "payment", template: true, capabilities: ["payment.sale", "payment.refund", "payment.cancel", "payment.status"] },
  },
  {
    key: "receipt_printer_connector_template",
    name: "Receipt Printer Connector Template",
    description: "Installable metadata template for a receipt-printer connector; requires a compatible local bridge.",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    category: "Connector Templates",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: { type: "receipt_printer", template: true, capabilities: ["printer.print", "printer.test", "printer.status"] },
  },
  {
    key: "kitchen_printer_connector_template",
    name: "Kitchen Printer Connector Template",
    description: "Installable metadata template for a kitchen-printer connector; requires a compatible local bridge.",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    category: "Connector Templates",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: { type: "kitchen_printer", template: true, capabilities: ["printer.kitchen.print", "printer.test", "printer.status"] },
  },
  {
    key: "cash_drawer_connector_template",
    name: "Cash Drawer Connector Template",
    description: "Installable metadata template for a cash-drawer connector; requires a compatible local bridge.",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    category: "Connector Templates",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: { type: "cash_drawer", template: true, capabilities: ["drawer.open", "drawer.test", "drawer.status"] },
  },
  {
    key: "mobile_scanner_connector",
    name: "Mobile Scanner Connector",
    description: "Send-only phone barcode scanner with one-till pairing and local-network-first connection.",
    route: "/app/settings/hardware",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    storeScoped: true,
    category: "Hardware Connectors",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: {
      type: "barcode_scanner",
      capabilities: ["barcode_scan", "pairing", "wifi_scanner", "device_health", "reconnect"],
      optionalCapabilities: ["bluetooth_scanner"],
      configurationSchema: [
        { key: "connectionMode", type: "string", default: "WIFI_QR", enum: ["WIFI_QR", "BLUETOOTH"] },
        { key: "wifiMode", type: "string", default: "LOCAL_ONLY", enum: ["LOCAL_ONLY", "SERVER_RELAY"] },
      ],
    },
  },
  {
    key: "barcode_scanner_connector_template",
    name: "Barcode Scanner Connector Template",
    description: "Installable metadata template for a barcode-scanner connector; requires a compatible local bridge.",
    permissions: ["integration.manage", "connector.test", "connector.view", "connector.manage"],
    category: "Connector Templates",
    billable: false,
    licenceRequired: false,
    dependencies: ["connector_core"],
    connectorApp: { type: "barcode_scanner", template: true, capabilities: ["scanner.enable", "scanner.disable", "scanner.test", "scanner.status"] },
  },
  {
    key: "uber_eats",
    name: "Uber Eats",
    description: "Uber Eats connection and online order integration.",
    route: "/app/integrations",
    permissions: ["online_orders.view", "online_orders.configure"],
    storeScoped: false,
    category: "Administration",
  },
  {
    key: "email_connector",
    name: "Email Connector",
    description: "Email communication provider for the shared Communication Core.",
    route: "/app/settings/email-delivery",
    permissions: ["integration.manage", "message.send"],
    storeScoped: false,
    category: "Communication",
    version: "1.1.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "communications.email",
    dependencies: ["communication_core"],
    capabilities: ["messaging", "customer_notifications", "provider_status"],
    providerConnector: {
      providerKey: "email",
      channel: "EMAIL",
      integrationType: "communication_provider",
      authentication: { type: "api_or_smtp", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["provider", "endpoint", "from_email", "api_key", "api_secret", "auth_scheme"],
      mappings: ["recipient_email", "subject", "message_template", "provider_message_id"],
      events: [
        "communication.message_received",
        "communication.message_sent",
        "communication.message_delivered",
        "communication.message_failed"
      ],
      actions: ["SEND_COMMUNICATION"],
    },
  },
  {
    key: "brevo_connector",
    packageKey: "brevo_connector",
    name: "Brevo Connect",
    description: "Brevo transactional email connector for onePOS Communication Core.",
    route: "/app/connector-settings/brevo_connector",
    permissions: ["integration.manage", "communications.send", "connector.test", "connector.view", "connector.manage"],
    storeScoped: false,
    category: "Communication",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: false,
    licenceRequired: false,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "communications.email",
    dependencies: ["connector_core", "communication_core"],
    capabilities: ["email_outbound", "provider_status"],
    iconAssetKey: "email",
    providerConnector: {
      providerKey: "brevo",
      channel: "EMAIL",
      integrationType: "communication_provider",
      authentication: { type: "api_key", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["fromEmail", "fromName", "apiKey"],
      mappings: ["recipient_email", "subject", "message_template", "provider_message_id"],
      events: ["communication.message_sent", "communication.message_delivered", "communication.message_failed"],
      actions: ["SEND_EMAIL_BREVO"],
    },
    connectorApp: {
      type: "communication",
      scope: "company",
      provider: "brevo",
      mode: "LIVE",
      capabilities: [
        { key: "email.send", requiredPermissions: ["communications.send"] },
        { key: "connector.test", requiredPermissions: ["integration.manage"] }
      ],
      testActions: [
        {
          key: "email.send",
          label: "Send test email",
          description: "Verify the full OneEngine to Brevo email delivery path.",
          endpoint: "/api/connector-instances/{instanceId}/send-test-email",
          permission: "communications.send",
          requiresEnabled: false,
          fields: [
            { key: "recipient", type: "email", required: true, maxLength: 320, label: "To email", placeholder: "name@example.com" },
            { key: "subject", type: "string", required: true, maxLength: 200, default: "Brevo Test", label: "Subject" },
            { key: "message", type: "string", required: true, maxLength: 2000, default: "It works I love chatGPT", label: "Message" }
          ]
        }
      ],
      configurationSchema: [
        { key: "fromEmail", type: "string", required: true, label: "Verified sender email", description: "Use a sender address already verified in Brevo. If you use a Gmail/Yahoo/Outlook address, Brevo may rewrite the From address to a brevosend.com address for deliverability. For a branded From address, verify a domain you own in Brevo and then use an address on that domain.", helpUrl: "https://app.brevo.com/senders/list", helpLabel: "Open Brevo sender settings" },
        { key: "fromName", type: "string", label: "Sender name", description: "This is the display name recipients see. For branded sending, use a verified sender on your own authenticated domain.", helpUrl: "https://app.brevo.com/senders/domain/list", helpLabel: "Set up sender domain" },
        { key: "apiKey", type: "secret", required: true, label: "Brevo API key", description: "Get this from Brevo > Settings > SMTP & API > API Keys.", helpUrl: "https://app.brevo.com/settings/keys/api", helpLabel: "Open Brevo API keys" }
      ],
    },
  },
  {
    key: "mailjet_connector",
    packageKey: "mailjet_connector",
    name: "Mailjet Connect",
    description: "Mailjet transactional email connector for onePOS Communication Core.",
    route: "/app/connector-settings/mailjet_connector",
    permissions: ["integration.manage", "communications.send", "connector.test", "connector.view", "connector.manage"],
    storeScoped: false,
    category: "Communication",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: false,
    licenceRequired: false,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "communications.email",
    dependencies: ["connector_core", "communication_core"],
    capabilities: ["email_outbound", "provider_status"],
    iconAssetKey: "email",
    providerConnector: {
      providerKey: "mailjet",
      channel: "EMAIL",
      integrationType: "communication_provider",
      authentication: { type: "basic", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["fromEmail", "fromName", "apiKey", "secretKey"],
      mappings: ["recipient_email", "subject", "message_template", "provider_message_id"],
      events: ["communication.message_sent", "communication.message_delivered", "communication.message_failed"],
      actions: ["SEND_EMAIL_MAILJET"],
    },
    connectorApp: {
      type: "communication",
      scope: "company",
      provider: "mailjet",
      mode: "LIVE",
      capabilities: [
        { key: "email.send", requiredPermissions: ["communications.send"] },
        { key: "connector.test", requiredPermissions: ["integration.manage"] }
      ],
      testActions: [
        {
          key: "email.send",
          label: "Send test email",
          description: "Verify the full OneEngine to Mailjet email delivery path.",
          endpoint: "/api/connector-instances/{instanceId}/send-test-email",
          permission: "communications.send",
          requiresEnabled: false,
          fields: [
            { key: "recipient", type: "email", required: true, maxLength: 320, label: "To email", placeholder: "name@example.com" },
            { key: "subject", type: "string", required: true, maxLength: 200, default: "Mailjet Test", label: "Subject" },
            { key: "message", type: "string", required: true, maxLength: 2000, default: "It works I love chatGPT", label: "Message" }
          ]
        }
      ],
      configurationSchema: [
        { key: "fromEmail", type: "string", required: true, label: "Verified sender email", description: "Use a sender address already validated in Mailjet. For a branded From address and better deliverability, validate a domain you own and use an address on that domain.", helpUrl: "https://app.mailjet.com/account/sender", helpLabel: "Open Mailjet sender settings" },
        { key: "fromName", type: "string", label: "Sender name", description: "This is the display name recipients see. Use a verified sender on your authenticated domain for branded sending.", helpUrl: "https://app.mailjet.com/account/sender", helpLabel: "Manage sender domain" },
        { key: "apiKey", type: "secret", required: true, label: "Mailjet API key", description: "Get this from Mailjet Account Settings > API Key Management.", helpUrl: "https://app.mailjet.com/account/apikeys", helpLabel: "Open Mailjet API keys" },
        { key: "secretKey", type: "secret", required: true, label: "Mailjet secret key", description: "Use the secret key paired with the selected Mailjet API key.", helpUrl: "https://app.mailjet.com/account/apikeys", helpLabel: "Open Mailjet API keys" }
      ],
    },
  },
  {
    key: "sms_connector",
    name: "SMS Connector",
    description: "SMS communication provider for the shared Communication Core.",
    route: "/app/settings/sms-delivery",
    permissions: ["integration.manage", "message.send"],
    storeScoped: false,
    category: "Communication",
    version: "1.1.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "communications.sms",
    dependencies: ["communication_core"],
    capabilities: ["messaging", "customer_notifications", "provider_status"],
    providerConnector: {
      providerKey: "sms",
      channel: "SMS",
      integrationType: "communication_provider",
      authentication: { type: "api", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["provider", "endpoint", "sender_id", "api_key", "api_secret", "auth_scheme"],
      mappings: ["recipient_phone", "message_template", "provider_message_id"],
      events: [
        "communication.message_received",
        "communication.message_sent",
        "communication.message_delivered",
        "communication.message_failed"
      ],
      actions: ["SEND_COMMUNICATION"],
    },
  },
  {
    key: "smsgate_connector",
    packageKey: "smsgate_connector",
    name: "SMSGate",
    description: "SMSGate Android SMS provider for onePOS Communication Core using username/password or API token authentication.",
    route: "/app/connector-settings/smsgate_connector",
    permissions: ["integration.manage", "communications.send", "connector.test", "connector.view", "connector.manage"],
    storeScoped: false,
    category: "Communication",
    version: "1.2.0",
    packageType: "APPLICATION",
    billable: false,
    licenceRequired: false,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "communications.sms",
    dependencies: ["connector_core", "communication_core", "sms_connector"],
    capabilities: ["sms_outbound", "sms_inbound", "provider_status", "device_discovery", "appointment_booking"],
    providerConnector: {
      providerKey: "smsgate",
      channel: "SMS",
      integrationType: "communication_provider",
      authentication: {
        type: "basic_or_bearer",
        defaultMode: "USERNAME_PASSWORD",
        credentialStorage: "integration_connections.credentials_encrypted"
      },
      settings: ["apiUrl", "authenticationMethod", "username", "password", "apiToken", "deviceId", "simNumber", "bookingBaseUrl", "webhookSigningKey"],
      mappings: ["recipient_phone", "message", "provider_message_id"],
      events: ["communication.message_received"],
      actions: ["SEND_COMMUNICATION", "TEST_CONNECTION", "LIST_DEVICES"],
    },
    connectorApp: {
      type: "communication",
      scope: "company",
      provider: "smsgate",
      mode: "LIVE",
      capabilities: [
        { key: "sms.send", requiredPermissions: ["communications.send"] },
        { key: "sms.devices.list", requiredPermissions: ["integration.manage"] },
        { key: "connector.test", requiredPermissions: ["integration.manage"] }
      ],
      testActions: [
        {
          key: "sms.send",
          label: "Send test SMS",
          description: "Verify the full onePOS to SMSGate to Android phone delivery path.",
          endpoint: "/api/connector-instances/{instanceId}/send-test-sms",
          permission: "communications.send",
          requiresEnabled: true,
          fields: [
            { key: "recipient", type: "tel", required: true, label: "Mobile number", placeholder: "+44..." },
            { key: "message", type: "string", required: true, maxLength: 500, default: "onePOS SMSGate test message", label: "Message" }
          ]
        }
      ],
      configurationSchema: [
        { key: "apiUrl", type: "string", required: true, default: "https://api.sms-gate.app", label: "API URL" },
        { key: "authenticationMethod", type: "picklist", required: true, default: "USERNAME_PASSWORD", enum: ["USERNAME_PASSWORD", "API_TOKEN"], label: "Authentication method" },
        { key: "username", type: "string", label: "Username" },
        { key: "password", type: "secret", label: "Password" },
        { key: "apiToken", type: "secret", label: "API token" },
        { key: "deviceId", type: "string", label: "Device ID" },
        { key: "simNumber", type: "number", label: "SIM number" },
        { key: "bookingBaseUrl", type: "string", default: "https://onesolutions-ahuja.github.io/OneEngine", label: "Public booking URL" },
        { key: "webhookSigningKey", type: "secret", label: "Webhook signing key" }
      ],
    },
  },
  {
    key: "whatsapp_connector",
    name: "WhatsApp Connector",
    description: "WhatsApp Business communication provider for the shared Communication Core.",
    route: "/app/integrations",
    permissions: ["integration.manage", "message.send"],
    storeScoped: false,
    category: "Communication",
    entitlementKey: "integrations",
    dependencies: ["communication_core"],
    capabilities: ["messaging", "customer_notifications", "provider_status"],
    providerConnector: {
      providerKey: "whatsapp",
      channel: "WHATSAPP",
      integrationType: "communication_provider",
      authentication: { type: "whatsapp_business", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["phone_number_id", "business_account_id", "webhook_verify_token", "security_mode"],
      mappings: ["recipient_phone", "message_template", "provider_message_id"],
      events: [
        "communication.message_received",
        "communication.message_sent",
        "communication.message_delivered",
        "communication.message_failed"
      ],
      actions: ["SEND_COMMUNICATION", "WHATSAPP_TEST_CONNECTION", "WHATSAPP_SYNC_MESSAGE_STATUS"],
    },
    iconAssetKey: "whatsapp",
  },
  {
    key: "whatsapp_assistant",
    name: "WhatsApp Assistant",
    description: "Workflow-driven WhatsApp Business assistant for customer enquiries, customer matching, templates and governed AI or rule-based replies.",
    route: "/app/settings/whatsapp-assistant",
    permissions: ["integration.manage", "message.send", "customer.view"],
    storeScoped: false,
    category: "Communication",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "whatsapp_assistant",
    dependencies: ["communication_core", "customers", "platform"],
    capabilities: [
      "whatsapp_inbound",
      "whatsapp_outbound",
      "customer_matching",
      "optional_customer_creation",
      "workflow_automation",
      "message_templates",
      "rule_based_replies",
      "ai_assisted_replies",
      "human_handoff",
      "audit"
    ],
    events: [
      { eventType: "communication.message_received", channel: "WHATSAPP", description: "A verified inbound WhatsApp message was received through Communication Core." },
      { eventType: "whatsapp_message_received", legacyAliasOf: "communication.message_received", description: "Legacy WhatsApp receive trigger kept for existing workflows." }
    ],
    workflowTemplates: [
      {
        key: "whatsapp_assistant_inbound",
        label: "WhatsApp Assistant - inbound message",
        triggerKey: "communication_message_received",
        channel: "WHATSAPP",
        activeByDefault: false,
        description: "Starter workflow for inbound WhatsApp communication. Review and activate explicitly."
      },
      {
        key: "whatsapp_assistant_handoff",
        label: "WhatsApp Assistant - human handoff",
        triggerKey: "communication_handoff",
        channel: "WHATSAPP",
        activeByDefault: false,
        description: "Starter workflow for human handoff. Review and activate explicitly."
      }
    ],
    providerConnector: {
      providerKey: "whatsapp",
      channel: "WHATSAPP",
      integrationType: "communication_provider",
      authentication: { type: "whatsapp_business", credentialStorage: "integrations.configuration.encrypted" },
      settings: [
        "phone_number_id",
        "business_account_id",
        "webhook_verify_token",
        "assistant_mode",
        "customer_match_mode",
        "create_customer_if_missing",
        "allowed_intents",
        "human_handoff_enabled",
        "ai_provider",
        "privacy_scope",
        "opt_out_enabled"
      ],
      mappings: ["customer_phone", "customer_id", "conversation_id", "message_template"],
      webhooks: ["messages", "message_status"],
      events: [
        "communication.message_received",
        "communication.message_sent",
        "communication.message_delivered",
        "communication.message_failed",
        "communication.opted_out",
        "communication.handoff"
      ],
      actions: ["SEND_COMMUNICATION"],
      workflowScope: {
        channel: "WHATSAPP",
        licenceAwareObjects: true,
        installedPackageObjectsOnly: true,
        reuseBuilder: true,
        reuseMessageTemplates: true
      }
    },
    iconAssetKey: "whatsapp",
  },
  {
    key: "quickbooks",
    name: "QuickBooks",
    description: "QuickBooks accounting connection and mapped exports.",
    route: "/app/integrations",
    permissions: ["integration.manage", "accounting.export"],
    storeScoped: false,
    category: "Finance",
    entitlementKey: "integrations",
    dependencies: ["integrations", "finance_core", "retail_pos", "customers", "supplier_core"],
    capabilities: ["accounting_export", "customer_sync", "supplier_sync", "product_mapping"],
    providerConnector: {
      providerKey: "quickbooks",
      integrationType: "accounting",
      authentication: { type: "oauth2", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["environment", "accounting_mode", "sync_customers", "sync_suppliers", "sync_products", "sync_sales", "sync_payments", "sync_refunds", "sync_purchases", "sync_supplier_payments", "sync_supplier_credits"],
      mappings: ["vat_code", "sales_income_account", "accounts_payable_account", "inventory_asset_account", "expense_account", "card_account", "cash_account", "payment_account", "refund_account", "discount_account", "service_charge_account", "delivery_account", "payment_method"],
      actions: ["CONNECTOR_TEST_CONNECTION"],
    },
  },
  {
    key: "shopify",
    name: "Shopify",
    description: "Shopify catalogue, inventory and online-order connection.",
    route: "/app/integrations",
    permissions: ["integration.manage", "online_orders.manage", "inventory.view"],
    storeScoped: true,
    category: "Commerce",
    entitlementKey: "integrations",
    dependencies: ["integrations", "products", "inventory", "customers", "online_orders", "retail_pos"],
    capabilities: ["catalogue_sync", "inventory_sync", "order_import", "fulfilment"],
    providerConnector: {
      providerKey: "shopify",
      integrationType: "online_orders",
      authentication: { type: "shopify_app", credentialStorage: "integration_connections.credentials_encrypted" },
      settings: ["shop_domain", "environment", "price_list_id", "default_store_id", "catalogue_sync", "inventory_sync", "order_import", "customer_linking"],
      mappings: ["product", "variant", "price", "store_location", "order_status", "fulfilment_status", "tax"],
      webhooks: ["orders/create", "orders/updated", "orders/fulfilled", "orders/cancelled", "refunds/create", "fulfillments/create", "fulfillments/update", "products/create", "products/update", "products/delete", "inventory_levels/update"],
      actions: ["CONNECTOR_TEST_CONNECTION", "SHOPIFY_PROCESS_WEBHOOK", "SHOPIFY_SYNC_PRODUCTS", "SHOPIFY_SYNC_INVENTORY", "SHOPIFY_EXPORT_FULFILMENT", "SHOPIFY_EXPORT_REFUND", "SHOPIFY_RETRY_FAILED_SYNC"],
    },
  },
  {
    key: "open_food_facts",
    name: "Open Food Facts",
    description: "Free worldwide barcode and product-name lookup using the Open Food Facts database.",
    route: "/app/global-products",
    permissions: ["global_product.view", "product.create", "integration.manage"],
    storeScoped: false,
    category: "Catalogue & Supply",
    version: "1.2.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    entitlementKey: "open_food_facts_connector",
    installable: true,
    visibility: "PUBLIC",
    dependencies: ["products"],
    providerConnector: {
      providerKey: "open_food_facts",
      integrationType: "product_lookup",
      authentication: { type: "none", credentialStorage: null },
      globalProductLookup: {
        providerKey: "open_food_facts",
        configKey: "global_product_lookup_open_food_facts",
        displayName: "Open Food Facts",
        baseUrl: "https://world.openfoodfacts.org",
        lookupEndpoint: "/api/v2/product/{barcode}.json",
        testEndpoint: "/api/v2/product/737628064502.json",
        authType: "none",
        timeoutMs: 5000,
        priority: 100,
        fallbackEnabled: true,
        cacheTtlSeconds: 5,
        configurableFields: ["baseUrl", "enabled", "priority", "timeoutMs", "fallbackEnabled", "cacheTtlSeconds", "userAgent"],
        fieldMappings: { barcode: "code", name: "product_name", brand: "brands", category: "categories", quantity: "quantity", imageUrl: "image_front_url", country: "countries" },
        searchEndpoint: "/cgi/search.pl",
        scope: "worldwide",
        actions: ["OPEN_FOOD_FACTS_SEARCH_PRODUCTS", "CONNECTOR_TEST_CONNECTION"],
      },
    },
  },
  {
    key: "upcitemdb",
    name: "UPCitemdb",
    description: "Worldwide UPC, EAN and GTIN product lookup with free and customer-key API modes.",
    route: "/app/global-products",
    permissions: ["global_product.view", "product.create", "integration.manage"],
    storeScoped: false,
    category: "Catalogue & Supply",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    entitlementKey: "upcitemdb_connector",
    installable: true,
    visibility: "PUBLIC",
    dependencies: ["products"],
    providerConnector: {
      providerKey: "upcitemdb",
      integrationType: "product_lookup",
      authentication: { type: "optional_api_key", credentialStorage: "integration_connections.credentials_encrypted" },
      globalProductLookup: {
        providerKey: "upcitemdb",
        configKey: "global_product_lookup_upcitemdb",
        displayName: "UPCitemdb",
        baseUrl: "https://api.upcitemdb.com",
        lookupEndpoint: "/prod/trial/lookup",
        paidLookupEndpoint: "/prod/v1/lookup",
        searchEndpoint: "/prod/trial/search",
        paidSearchEndpoint: "/prod/v1/search",
        authType: "optional_user_key",
        timeoutMs: 7000,
        priority: 200,
        fallbackEnabled: false,
        cacheTtlSeconds: 30,
        configurableFields: ["baseUrl", "enabled", "priority", "timeoutMs", "fallbackEnabled", "cacheTtlSeconds"],
        fieldMappings: { barcode: "ean", name: "title", brand: "brand", description: "description", category: "category", imageUrl: "images.0" },
        scope: "worldwide",
        actions: ["UPCITEMDB_LOOKUP_PRODUCT", "UPCITEMDB_SEARCH_PRODUCTS", "UPCITEMDB_TEST_CONNECTION"],
      },
    },
  },
  {
    key: "barcode_nest",
    name: "BarcodeNest",
    description: "BarcodeNest UPC, EAN and GTIN lookup using a customer-provided API key.",
    route: "/app/global-products",
    permissions: ["global_product.view", "product.create", "integration.manage"],
    storeScoped: false,
    category: "Catalogue & Supply",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    entitlementKey: "barcode_nest_connector",
    installable: true,
    visibility: "PUBLIC",
    dependencies: ["products"],
    providerConnector: {
      providerKey: "barcode_nest",
      integrationType: "product_lookup",
      authentication: { type: "x_api_key", credentialStorage: "integration_connections.credentials_encrypted" },
      globalProductLookup: {
        providerKey: "barcode_nest",
        configKey: "global_product_lookup_barcode_nest",
        displayName: "BarcodeNest",
        baseUrl: "https://api.barcodenest.com",
        lookupEndpoint: "/v1/products/{barcode}",
        authType: "x-api-key",
        timeoutMs: 7000,
        priority: 300,
        fallbackEnabled: false,
        cacheTtlSeconds: 30,
        configurableFields: ["baseUrl", "enabled", "priority", "timeoutMs", "fallbackEnabled", "cacheTtlSeconds"],
        fieldMappings: { name: "name", brand: "brand", category: "categories", quantity: "quantity", imageUrl: "image_url", country: "countries" },
        scope: "worldwide",
        actions: ["BARCODENEST_LOOKUP_PRODUCT", "BARCODENEST_TEST_CONNECTION"],
      },
    },
  },
  {
    key: "go_upc",
    name: "Go-UPC",
    description: "Live barcode product lookup using your company-provided Go-UPC API key.",
    route: "/app/global-products",
    permissions: ["global_product.view", "product.create", "integration.manage"],
    storeScoped: false,
    category: "Catalogue & Supply",
    version: "1.0.0",
    entitlementKey: "go_upc_connector",
    dependencies: ["products"],
    providerConnector: {
      providerKey: "go_upc",
      integrationType: "product_lookup",
      authentication: { type: "bearer_api_key", credentialStorage: "integration_connections.credentials_encrypted" },
      globalProductLookup: {
        providerKey: "go_upc",
        configKey: "global_product_lookup_go_upc",
        displayName: "Go-UPC",
        baseUrl: "https://go-upc.com",
        lookupEndpoint: "/api/v1/code/{barcode}",
        testEndpoint: "/api/v1/code/737628064502",
        authType: "bearer",
        timeoutMs: 5000,
        priority: 100,
        fallbackEnabled: true,
        cacheTtlSeconds: 5,
        configurableFields: ["baseUrl", "enabled", "priority", "timeoutMs", "fallbackEnabled", "cacheTtlSeconds"],
        fieldMappings: { barcode: "barcode", name: "name", brand: "brand", description: "description", category: "category", imageUrl: "image_url" },
        actions: ["GO_UPC_LOOKUP_PRODUCT", "CONNECTOR_TEST_CONNECTION"],
      },
    },
  },
  {
    key: "client_web_shop",
    name: "Client Web Shop",
    description: "Public storefront, cart, checkout, order creation and own-delivery package for client commerce.",
    route: "/app/settings/client-web-shop",
    permissions: ["online_orders.view", "online_orders.manage", "settings.manage", "customer.view"],
    storeScoped: true,
    category: "Commerce",
    version: "1.0.0",
    entitlementKey: "client_web_shop",
    dependencies: ["products", "inventory", "online_orders", "retail_pos", "customers"],
    capabilities: ["shopfront", "cart", "checkout", "order_creation", "public_tracking"],
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
  },
  {
    key: "own_delivery",
    name: "Own Delivery",
    description: "Driver assignment, delivery workspace, route planning and status updates for client fulfilment.",
    route: "/app/own-delivery",
    permissions: ["online_orders.view", "online_orders.manage", "delivery.driver", "user.view", "settings.manage"],
    storeScoped: true,
    category: "Operations",
    version: "1.0.0",
    entitlementKey: "delivery",
    dependencies: ["client_web_shop", "online_orders", "staff"],
    capabilities: ["driver_assignment", "delivery_workspace", "route_planning", "status_updates", "audit"],
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
  },
  {
    key: "one_kiosk",
    packageKey: "one_kiosk",
    name: "OneKiosk",
    description: "Customer self-service ordering and collection workflow for restaurants, retail, electronics and other counter-service businesses.",
    route: "/app/kiosk-devices",
    permissions: ["sale.create", "online_orders.view", "online_orders.manage"],
    storeScoped: true,
    category: "Operations",
    version: "1.0.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "one_kiosk",
    dependencies: ["products", "online_orders", "retail_pos"],
    optionalDependencies: ["connector_core"],
    iconAssetKey: "default-app",
    capabilities: [
      "kiosk_catalogue",
      "kiosk_cart",
      "kiosk_fulfilment",
      "kiosk_collection_number",
      "kiosk_order_display",
      "kiosk_responsive_touch_ui",
      "kiosk_payment_connectors"
    ],
    kiosk: {
      deploymentTargets: ["ANDROID", "WINDOWS", "BROWSER", "PWA"],
      layouts: ["AUTO", "TABLET", "DESKTOP", "PORTRAIT_KIOSK", "LANDSCAPE_KIOSK"],
      fulfilmentTypes: ["COLLECT", "EAT_IN", "TAKEAWAY", "COUNTER_SERVICE"],
      lifecycle: ["RECEIVED", "PREPARING", "READY", "COLLECTED"]
    }
  },
  {
    key: "one_assistant",
    packageKey: "one_assistant",
    name: "OneAssistant",
    description: "Workflow-first appointment booking, calendar and conversational booking automation with optional communication and payment connectors.",
    route: null,
    permissions: ["appointments.view", "appointments.manage", "appointments.configure", "appointments.payment"],
    storeScoped: false,
    category: "Business",
    version: "1.2.0",
    packageType: "APPLICATION",
    billable: true,
    licenceRequired: true,
    licenceMode: "COMMERCIAL",
    installable: true,
    visibility: "PUBLIC",
    entitlementKey: "one_assistant",
    dependencies: ["customers", "platform"],
    optionalDependencies: ["email_connector", "sms_connector", "whatsapp_connector", "communication_core", "connector_core"],
    capabilities: ["appointments","appointment_calendar","appointment_availability","appointment_slot_holds","appointment_payments","conversation_sessions","workflow_automation","human_handoff","email_booking","sms_booking","whatsapp_booking","public_booking_links","capability_subflows"],
    events: [
      { eventType: "appointment.slot_held", description: "A temporary appointment slot hold was created." },
      { eventType: "appointment.payment_required", description: "A booking requires an advance payment before confirmation." },
      { eventType: "appointment.confirmed", description: "An appointment was confirmed." },
      { eventType: "appointment.cancelled", description: "An appointment was cancelled." },
      { eventType: "appointment.booking_case_created", description: "An inbound communication was converted into a booking case." },
      { eventType: "appointment.slot_selected", description: "A customer selected a slot from a public booking link." }
    ],
    workflowTemplates: [
      {
        key: "one_assistant_booking_router",
        label: "OneAssistant - Booking channel router",
        triggerKey: "communication_message_received",
        activeByDefault: false,
        description: "Inspect the inbound channel/message intent, create a booking case, then call the matching communication subflow."
      },
      {
        key: "one_assistant_email_booking",
        label: "OneAssistant - Email booking",
        triggerKey: "communication_message_received",
        channel: "EMAIL",
        subflowCapability: "assistant.communication.EMAIL",
        requiredPackageKey: "email_connector",
        activeByDefault: false,
        description: "Email-to-case booking flow: send an expiring public booking link, then payment and confirmation messages."
      },
      {
        key: "one_assistant_sms_booking",
        label: "OneAssistant - SMS booking",
        triggerKey: "communication_message_received",
        channel: "SMS",
        subflowCapability: "assistant.communication.SMS",
        requiredPackageKey: "sms_connector",
        activeByDefault: false,
        description: "SMS booking subflow using the same appointment case and booking-link engine."
      },
      {
        key: "one_assistant_whatsapp_booking",
        label: "OneAssistant - WhatsApp booking",
        triggerKey: "communication_message_received",
        channel: "WHATSAPP",
        subflowCapability: "assistant.communication.WHATSAPP",
        requiredPackageKey: "whatsapp_connector",
        activeByDefault: false,
        description: "WhatsApp booking subflow using the same appointment case and booking engine."
      },
      {
        key: "one_assistant_payment_router",
        label: "OneAssistant - Payment router",
        triggerKey: "appointment_payment_required",
        subflowCapability: "assistant.payment",
        activeByDefault: false,
        description: "Resolve an installed payment-provider subflow. Provider-specific flows finish with Complete Appointment Payment."
      },
      {
        key: "one_assistant_confirmation_router",
        label: "OneAssistant - Confirmation router",
        triggerKey: "appointment_confirmed",
        subflowCapability: "assistant.confirmation",
        activeByDefault: false,
        description: "Send the channel-specific confirmation/invoice template after the appointment is confirmed."
      }
    ],
    subflowContracts: {
      communication: ["assistant.communication.EMAIL","assistant.communication.SMS","assistant.communication.WHATSAPP"],
      payment: "assistant.payment",
      confirmation: "assistant.confirmation",
      paymentCompletionAction: "COMPLETE_APPOINTMENT_PAYMENT",
      resolverAction: "RUN_ASSISTANT_SUBFLOW"
    }
  },
  {
    key: "platform",
    name: "OneDeveloper",
    description: "Developer workspace for configurable objects, metadata, apps and workflow administration.",
    route: "/app/developer",
    permissions: ["settings.manage"],
    storeScoped: false,
    category: "Administration",
  },
];

export const internalAppCatalog = Object.freeze(
  CATALOG.map((entry) => Object.freeze({
    ...entry,
    route: entry.route || "/app/integrations",
    permissions: Object.freeze([...entry.permissions]),
  }))
);

export const internalAppCatalogSchema = `
  ALTER TABLE platform_modules ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;
  CREATE TABLE IF NOT EXISTS platform_module_access (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    module_id UUID NOT NULL REFERENCES platform_modules(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
  CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_module_access_scope
    ON platform_module_access(module_id, company_id, COALESCE(store_id, '00000000-0000-0000-0000-000000000000'::uuid));
  CREATE INDEX IF NOT EXISTS idx_platform_module_access_company
    ON platform_module_access(company_id, store_id, enabled);
`;

export function catalogEntry(moduleKey) {
  return internalAppCatalog.find((entry) => entry.key === moduleKey) || null;
}

export function hasCatalogPermission(entry, permissions = [], _legacyAuthority = false) {
  return entry.permissions.some((permission) => permissions.includes(permission));
}

export async function seedInternalAppCatalog(pool) {
  for (const entry of internalAppCatalog) {
    await pool.query(
      `INSERT INTO platform_modules (module_key, name, version, description, installed, metadata)
       VALUES ($1, $2, '1.0.0', $3, TRUE, $4::jsonb)
       ON CONFLICT (module_key) DO UPDATE SET
         name=EXCLUDED.name,
         description=EXCLUDED.description,
         metadata=EXCLUDED.metadata,
         updated_at=NOW()`,
      [entry.key, entry.name, entry.description, JSON.stringify(entry)]
    );
  }
}
