import { ConnectorRuntimeError } from "./connectorRuntime.js";

export const PAYPAL_QR_CAPABILITIES=Object.freeze(["connector.health","connector.test","http.request","webhook.verify"]);

function paypalBaseUrl(environment){return environment==="LIVE"?"https://api-m.paypal.com":"https://api-m.sandbox.paypal.com";}

export function createPaypalHttpAdapter({environment,clientId,clientSecret,fetchImpl=globalThis.fetch}={}){
 const baseUrl=paypalBaseUrl(environment);if(typeof fetchImpl!=="function")throw new TypeError("PayPal adapter requires fetch");
 async function accessToken(){const response=await fetchImpl(`${baseUrl}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});if(!response.ok)throw new ConnectorRuntimeError("PROVIDER_AUTH_FAILED","PayPal authentication failed",{retryable:response.status>=500});return(await response.json()).access_token;}
 async function request(path,options={}){const token=await accessToken();const response=await fetchImpl(`${baseUrl}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new ConnectorRuntimeError("PROVIDER_ERROR","PayPal API request failed",{retryable:response.status>=500});return{status:response.status,data:body};}
 async function verifyWebhook({webhookId,headers,body}){const result=await request("/v1/notifications/verify-webhook-signature",{method:"POST",body:JSON.stringify({auth_algo:headers["paypal-auth-algo"],cert_url:headers["paypal-cert-url"],transmission_id:headers["paypal-transmission-id"],transmission_sig:headers["paypal-transmission-sig"],transmission_time:headers["paypal-transmission-time"],webhook_id:webhookId,webhook_event:body})});return result.data?.verification_status==="SUCCESS";}
 return{accessToken,request,verifyWebhook};
}

export function createPaypalQrDriver(){return{packageKey:"paypal_qr",capabilities:PAYPAL_QR_CAPABILITIES,createAdapter({configuration={}}){const environment=String(configuration.environment||"SANDBOX").toUpperCase(),clientId=String(configuration.clientId||"").trim(),clientSecret=String(configuration.clientSecret||"").trim(),provider=clientId&&clientSecret?createPaypalHttpAdapter({environment,clientId,clientSecret}):null;return{async connect(){if(!provider)throw new ConnectorRuntimeError("SETUP_REQUIRED","PayPal credentials are incomplete");await provider.accessToken();return{healthy:true,code:"CONNECTED"};},async healthCheck(){try{await this.connect();return{healthy:true,code:"CONNECTED"};}catch(error){return{healthy:false,code:error?.code||"ERROR",message:error?.message};}},async test(){const health=await this.healthCheck();return{success:health.healthy,status:health.code,message:health.message||null};},async execute(actionKey,payload={}){if(actionKey==="connector.health")return this.healthCheck();if(actionKey==="connector.test")return this.test();if(actionKey==="webhook.verify")return{verified:await provider.verifyWebhook(payload)};if(actionKey==="http.request"){if(!provider)throw new ConnectorRuntimeError("SETUP_REQUIRED","PayPal credentials are incomplete");return provider.request(String(payload.path||""),{method:String(payload.method||"GET").toUpperCase(),headers:payload.headers||{},...(payload.body===undefined?{}:{body:typeof payload.body==="string"?payload.body:JSON.stringify(payload.body)})});}throw new ConnectorRuntimeError("PROVIDER_NOT_SUPPORTED",`PayPal adapter does not support ${actionKey}; business payment behaviour belongs in metadata Flow`);}};}};}
