import { uberEatsWorkflowDefinitions } from "./workflows.js";

export function uberEatsManifest() {
  return {
    workflows: uberEatsWorkflowDefinitions(),
    objects: [
          {
            objectKey: "uber_eats_connection",
            metadataScope: "global",
            label: "Uber Eats Connection",
            pluralLabel: "Uber Eats Connections",
            description: "Tenant-scoped connection status for Uber Eats. Client credentials remain in the existing integration configuration and are not exposed as Platform fields.",
            sourceTable: "integrations",
            fields: [
              { apiName: "name", label: "Connection Name", fieldType: "text", writable: false },
              { apiName: "provider", label: "Provider", fieldType: "text", required: true, writable: false },
              { apiName: "active", label: "Active", fieldType: "boolean", writable: false },
              { apiName: "created_at", label: "Created", fieldType: "datetime", writable: false },
              { apiName: "updated_at", label: "Updated", fieldType: "datetime", writable: false },
            ],
          },
        ],
        permissionDeclarations: [
          { key: "connection_status", permission: "online_orders.view", access: "read" },
          { key: "connector_actions", permission: "online_orders.configure", access: "execute" },
          { key: "order_lifecycle", permission: "online_orders.manage", access: "execute" },
        ],
        actions: [
          {
            actionKey: "uber_eats.get_stores",
            objectKey: "uber_eats_connection",
            label: "Get Uber Eats Stores",
            description: "Run the editable Uber Eats Get Stores flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_GET_STORES" },
          },
          {
            actionKey: "uber_eats.test_connection",
            objectKey: "uber_eats_connection",
            label: "Test Uber Eats Connection",
            description: "Run the editable Uber Eats Test Connection flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_TEST_CONNECTION" },
          },
          {
            actionKey: "uber_eats.upload_menu",
            objectKey: "uber_eats_connection",
            label: "Upload Uber Eats Menu",
            description: "Run the editable Uber Eats Upload Menu flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_UPLOAD_MENU" },
          },
          {
            actionKey: "uber_eats.accept_order",
            objectKey: "uber_eats_connection",
            label: "Accept Uber Eats Order",
            description: "Run the editable Uber Eats Accept Order flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.manage",
            config: { subflowApiName: "GPT_UBER_EATS_ACCEPT_ORDER" },
          },
          {
            actionKey: "uber_eats.deny_order",
            objectKey: "uber_eats_connection",
            label: "Deny Uber Eats Order",
            description: "Run the editable Uber Eats Deny Order flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.manage",
            config: { subflowApiName: "GPT_UBER_EATS_DENY_ORDER" },
          },
          {
            actionKey: "uber_eats.update_item_price",
            objectKey: "uber_eats_connection",
            label: "Update Uber Eats Item Price",
            description: "Run the editable Uber Eats Update Item Price flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_UPDATE_ITEM_PRICE" },
          },
          {
            actionKey: "uber_eats.set_item_unavailable",
            objectKey: "uber_eats_connection",
            label: "Set Uber Eats Item Unavailable",
            description: "Run the editable Uber Eats Set Item Unavailable flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_SET_ITEM_UNAVAILABLE" },
          },
          {
            actionKey: "uber_eats.set_item_available",
            objectKey: "uber_eats_connection",
            label: "Set Uber Eats Item Available",
            description: "Run the editable Uber Eats Set Item Available flow.",
            handlerKey: "RUN_SUBFLOW",
            requiredPermission: "online_orders.configure",
            config: { subflowApiName: "GPT_UBER_EATS_SET_ITEM_AVAILABLE" },
          },
        ],
        buttons: [
          { buttonKey: "uber_eats_get_stores", objectKey: "uber_eats_connection", label: "Get Stores", actionKey: "uber_eats.get_stores", requiredPermission: "online_orders.configure", variant: "secondary" },
          { buttonKey: "uber_eats_test_connection", objectKey: "uber_eats_connection", label: "Test Connection", actionKey: "uber_eats.test_connection", requiredPermission: "online_orders.configure", variant: "secondary" },
          { buttonKey: "uber_eats_upload_menu", objectKey: "uber_eats_connection", label: "Upload Menu", actionKey: "uber_eats.upload_menu", requiredPermission: "online_orders.configure", variant: "primary" },
        ],
        mappingSchema: [
          {
            key: "store",
            scope: "company",
            source: "integrations.configuration.store_id",
            externalKey: "integrations.configuration.store_location_id",
            target: "stores.id",
            override: "company-selected-store",
          },
          {
            key: "product",
            scope: "company",
            source: "products.uber_item_id",
            externalKey: "Uber Eats item id",
            eligibility: "products.available_on_uber",
            override: "preserve-explicit-product-item-id",
          },
        ],
        workflows: [
          ...uberEatsWorkflowDefinitions(),
          {
            key: "uber_eats_menu_sync_after_product_save",
            label: "Uber Eats menu sync after product save",
            objectKey: "product",
            triggerKey: "after_save",
            activeByDefault: false,
            conditions: [{ field: "available_on_uber", operator: "equals", value: true }],
            action: {
              type: "workflow",
              actions: [
                {
                  id: "sync_menu",
                  key: "RUN_SUBFLOW",
                  subflowApiName: "GPT_UBER_EATS_UPLOAD_MENU",
                },
              ],
            },
          },
        ],
        forms: [
          {
            formKey: "uber_eats_connection",
            label: "Uber Eats Connection",
            permission: "online_orders.configure",
            fields: [
              { key: "environment", label: "Environment", source: "integrations.configuration.environment", editableBy: "existing-online-platform-settings" },
              { key: "client_id", label: "Client ID", source: "integrations.configuration.client_id", sensitive: true, editableBy: "existing-online-platform-settings" },
              { key: "client_secret", label: "Client Secret", source: "integrations.configuration.client_secret", sensitive: true, editableBy: "existing-online-platform-settings" },
              { key: "store_id", label: "onePOS Store", source: "integrations.configuration.store_id", editableBy: "existing-online-platform-settings" },
            ],
          },
        ],
        pages: [
          {
            pageKey: "uber_eats",
            label: "Uber Eats",
            routePath: "/app/custom/uber_eats",
            runtimeComponent: "uber_eats_settings",
            permissions: ["online_orders.view", "online_orders.configure"],
            definition: {
              presentation_mode: "landing",
              runtime_component: "uber_eats_settings",
              required_permissions: ["online_orders.view"],
              form_key: "uber_eats_connection",
              mapping_schema: [
                { key: "store", path: "integrations.configuration.store_id", external_key: "integrations.configuration.store_location_id" },
                { key: "product", path: "products.uber_item_id", eligibility: "products.available_on_uber" },
              ],
              forms: [
                { key: "environment", component_key: "picklist", source: "integrations.configuration.environment", permission: "online_orders.configure" },
                { key: "client_id", component_key: "text_input", source: "integrations.configuration.client_id", sensitive: true, permission: "online_orders.configure" },
                { key: "client_secret", component_key: "text_input", source: "integrations.configuration.client_secret", sensitive: true, permission: "online_orders.configure" },
                { key: "store_id", component_key: "lookup", source: "integrations.configuration.store_id", permission: "online_orders.configure" },
              ],
              sections: [
                { id: "uber-eats-connection", label: "Uber Eats Connection", columns: 1 },
                { id: "uber-eats-mapping", label: "Product Mapping", columns: 1 },
              ],
              components: [
                { id: "uber-eats-heading", section_id: "uber-eats-connection", component_key: "header", label: "Uber Eats" },
                { id: "uber-eats-settings", section_id: "uber-eats-connection", component_key: "text", label: "Manage credentials and store selection in the existing Online Platforms settings. Secrets are never displayed in this package page." },
                { id: "uber-eats-mapping-info", section_id: "uber-eats-mapping", component_key: "text", label: "Product availability and item IDs use the existing Product Master fields available_on_uber and uber_item_id." },
              ],
            },
          },
        ],
        listViews: [
          {
            objectKey: "uber_eats_connection",
            viewKey: "connection_status",
            label: "Connection Status",
            description: "Uber Eats connection status without exposing client credentials.",
            columns: ["name", "provider", "active", "updated_at"],
            filters: { provider: "uber" },
            isDefault: true,
          },
        ],
      };
}
